--- #YAML:1.0
name:               Cellucidate
version:            0.02
abstract:           Perl library for cellucidate.com
author:
    - Brian Kaney <brian@vermonster.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Headers:  5.827
    REST::Client:   134
    XML::Simple:    2.18
resources:
    homepage:    http://cellucidate.com/api
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/cellucidate/perl-Cellucidate
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
